### ISSUE TITLE
Make sidenav narrower

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#1119]
Let's update the [Sidenav](https://operational-ui.netlify.com/#!/Sidenav) in compact mode to:

- make it thinner – 64px
- remove labels, use tooltips instead

This will look better I think.

**Comment by jm1200** [comment]
I'd like to give this issue a go. 

Making the Sidenav in compact mode thinner: Looks like I can just make a change to constants.ts:

`const constants = {
 ...
  compactSidebarWidth: 64,
  ...
}`

For the tooltips, are you thinking of having a tool tip appear just to the right of the icons?

**Comment by micha-f** [comment]
Exactly - tooltips to the right of the icons. This is the style we have in mind:

![image](https://user-images.githubusercontent.com/200647/60668586-a09fe200-9e6c-11e9-8a17-722be791a43a.png)

The compact sidenav is for UIs that are used on a regular basis - so we want to keep it slim and simple.

**Comment by TejasQ** [comment]
@jm1200 do you feel up to it? If so, I can assign it to you and we can get this ship in the sky. 🚀

**Comment by jm1200** [comment]
Yup, I'll take it.

**Comment by jm1200** [comment]
So, I have been playing around with trying to get tooltips instead of labels and I am stuck. Please feel free to give this issue to someone more capable. Or, if someone doesn't mind guiding me that would be great too.

In SidenavItem.tsx, the StyledSidenavItem component has two events, onMouseEnter and onMouseLeave that I thought might be useful. 

```
onMouseEnter={() => Boolean(items) && setIsOpen && setIsOpen(true)}
onMouseLeave={() => Boolean(items) && setIsOpen && setIsOpen(false)}
```
My thinking was that I can add something like this:

```
const [tooltip, setTooltip] = React.useState(false);
const handleOnMouseEnter = (items)=>{
    setTooltip(true)
    return Boolean(items) && setIsOpen && setIsOpen(true)
}
const handleOnMouseLeave= ()=>{
    setTooltip(false)
    return Boolean(items) && setIsOpen && setIsOpen(false)
}
```
Then, pass those functions to the events in StyledSidenavItem:
```
onMouseEnter={handleOnMouseEnter}
onMouseLeave={handleOnMouseLeave}
```

Then get rid of the labels and add a tooltip like so:
```
{compact ? tooltip ? <Tooltip right>{label}</Tooltip> : null  : label}
```

I tried variations of the above thought process and was unable to get a Tooltip to appear in the right place. Also, if the SidenavItem has a <Popout>, the tooltip will need to disappear. For that, maybe we can watch the "isOpen" variable and not render a <Tooltip> if it is false? 

I may have jumped in too early on trying to contribute. I should probably spend more time watching and reading how other people fix issues.

**Comment by TejasQ** [comment]
That's a great outlining of your thoughts, @jm1200! Want to hop on a call and pair program together?

**Comment by jm1200** [comment]
That would be great! I am free for the next 3 hours if you'd like to do that soon. What do you use to chat and pair program?

**Comment by TejasQ** [comment]
Sorry, @jm1200! I was away for the weekend. Maybe [hop on here](https://calendly.com/tejaskumar/pair-programming) and let's schedule something!

**Comment by jm1200** [comment]
I am going away for a couple of weeks and am not sure how much time I will have to work on this. I will keep an eye on it and see how it gets solved.

**Comment by TejasQ** [comment]
This is a more time-sensitive issue. Would you mind if I took it over? There'll be other fun issues to work on together.

**Comment by jm1200** [comment]
Absolutely! Thanks so much for trying to work on it with me. I am going away with my family for the next few weeks. I will try to keep an eye on it to keep learning. 

Cheers,
John
    On Friday, July 12, 2019, 04:49:18 p.m. GMT+4, Tejas Kumar <notifications@github.com> wrote:  
 
 
This is a more time-sensitive issue. Would you mind if I took it over? There'll be other fun issues to work on together.

**Comment by TejasQ** [comment]
@jm1200 there's a PR that implements it if you're still interested ^ 💞
