### ISSUE TITLE
Select's width increases when the drop-down opens

### ISSUE THREAD

**Issue by mpotomin** [contiamo/operational-ui#1311]
See the animation for more details:

![123](https://user-images.githubusercontent.com/639406/76434844-85e81a80-63b6-11ea-8e85-4077c74ce010.gif)

**Comment by rimildeyjsr** [comment]
@mpotomin - Hey! can I work on this?

**Comment by mpotomin** [comment]
> @mpotomin - Hey! can I work on this?

Sure @rimildeyjsr, go for it 😍

**Comment by rimildeyjsr** [comment]
@mpotomin Thanks 😄 Will tag you when I have a solution!

**Comment by rimildeyjsr** [comment]
@mpotomin - Hey I found the issue, but need some help for the solution 😅 

The select input (for custom field) is using the `<Form>` for the custom input, which has the following style on it:

```
// Space between siblings inside children inside groups
  "> * > *:not(:last-child)": {
    marginRight: theme.space.small,
  },
```

So this margin-right is increasing the width. I can't remove it since it removes the space between children inside groups

<img width="336" alt="Screenshot 2020-07-17 at 11 49 24 PM" src="https://user-images.githubusercontent.com/10229595/87818518-4e1f4100-c888-11ea-851a-bde9bbfa8592.png">

How to proceed here?

**Comment by mpotomin** [comment]
Hey @rimildeyjsr, good catch with the margin styling of the Form! I think the simplest solution would to use a `<div>` wrapper  instead of the `<Form>` to avoid the margin side-effect. What do you think?

**Comment by rimildeyjsr** [comment]
@mpotomin - Nice idea! I think that solves the problem 😄 Sending in a PR!

**Comment by rimildeyjsr** [comment]
@mpotomin - On second thoughts, I think wrapping it in a fragment would be better, it would avoid that extra `<div>`
