### ISSUE TITLE
Select & context menu improvements

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/operational-ui#319]
* options are currently specified as `{ value: string, option?: string }`. Actually, options are treated in the code as always specified, and there are runtime errors when they are omitted.
* we should consider removing options altogether, and have the component simply take a list of strings. This would make the component much easier to use, and leave the minimal responsibility of mapping the labels to raw values to the library user. If need be, they can produce a wrapper that restores the current API with very minimal code.
* a redesign to match `DatePicker` is in order, adding a minimum width to look good.
* when the values pop up, their design should match `ContextMenu`.
* redesign the label to be consistent with input and date picker.

**Comment by TejasQ** [comment]
I'm not so sure about options being plain strings, because per the HTML [`<option>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) spec, it's pretty expected to supply a `value` to the option in case you want to have a different label than its value.

A use case in particular that I think of is the Singtel tool: we want options that have a value that the _backend_ understands (node id: 432), but we want to show a user a label that _the user_ understands: "my_menu_123". I think this is a fairly common use case and functionality that we ought to support out of the box for this reason, but also for idiomaticity with the native HTML `<option>` API.

**Comment by peterszerzo** [comment]
Maybe it's helpful to write it out a bit better how you would use the new API in the mindset of the old one:
```
render() {
  const optionsByOldApi = [
    { value: "v1", label: "l1" },
    { value: "v2", label: "l2" },
    { value: "v3", label: "l3" }
  ]
  return (
    <Select options={optionsByOldApi.map(o => o.label)} onChange={(newLabel, newIndex) => {
      // Either find the value by matching against the label, or just go by index
      // Keep doing business as usual
    } />
  )
}
```
Select is easier to use now, the `<option>` tag still gets a semantic value, and you can map things back quickly.

**Comment by TejasQ** [comment]
I like this, but I'd adjust it as so:

```jsx
render() {
  const optionsByOldApi = [
    { value: "v1", label: "l1" },
    { value: "v2", label: "l2" },
    { value: "v3", label: "l3" }
  ]
  return (
    <Select options={optionsByOldApi.map(o => o.label)} onChange={({ value, label }) => {
      /* do something with the value or label of the NEWLY SELECTED OPTION */
    } />
  )
}
```

Of course, we'll also have to consider multi-select.

**Comment by peterszerzo** [comment]
I'm noticing that `Select` and `ContextMenu` do very similar things (render a dropdown with items in it on click, react to selections). I think it still makes sense to have the two components around for semantics (what would a UI library be without a `Select`), but I think we are needlessly duplicating a lot of logic.

I have two alternatives in mind to proceed:

## 1. Re-use as much of the implementation as possible

* `ContextMenu` accepts `search` and `onSearch` props. If present, context menu renders a search bar similar to `SelectFilter` and passes changes back to the parent component.
* `Select` API stays the same (sans async methods that we already planned to remove), and uses this feature-complete `ContextMenu` under the hood. Only custom thing to render will be the label + datepicker-like input+downward pointing chevron thing. We should find a way to re-use that as well.

If we're concerned about having one publicly exposed component import another one in its implementation, we can create a private `Dropdown` component that is imported into both places. That can have a very flexible low-level API that both components can re-use.

## 2. Barebones HTML select, fancy context menu

This is the same as before for `ContextMenu`, but `Select` would turn into a native HTML `<select>` + `<option>` solution, the way https://peterszerzo.github.io/elm-natural-ui/#select does it (public-facing API stays the same as we agreed above).

Users can still reproduce the old-school select with a `ContextMenu`, but have a fully barebones semantic option that behaves well on phones etc.

I favor number two.

**Comment by TejasQ** [comment]
I favor number 1 because it seems like better design and will provide two very well thought through, robust components to serve both purposes of `Select` _and_ `ContextMenu`.

I favor number 2 because it delegates the power to ContextMenu, while allowing for something simpler if needed.

I favor both approaches and your engineering skills and _literally cannot decide_. Sorry I'm not much help, but if it was up to me, I'd say do whatever seems best to you. ¯\_(ツ)_/¯

**Comment by peterszerzo** [comment]
Awesome, let's see how it feels once implemented!

**Comment by TejasQ** [comment]
@peterszerzo can we close this?

**Comment by peterszerzo** [comment]
It's a bit up in the air right now until we find tangible uses for the context menu component. I'd leave it open.

**Comment by TejasQ** [comment]
Since we've found tangible uses, can we close this and reopen a new issue if it becomes relevant?
