### ISSUE TITLE
Improve CI scripts

### ISSUE THREAD

**Issue by micha-f** [Contiamo/operational-ui#331]
- We should run all tests on CI
- We should run lint and prettier without --fix and fail
=> that's what CI is for

**Comment by peterszerzo** [comment]
Agree with the first point, I'll get that fixed.

Re:the second one: that's the `npm run ensure:clean:repo` is for - we run without fix, and if anything changes in the repo, we fail in the end. It's because linter and prettier step on each others' toes, and it is guaranteed that one will fail if they're run sequentially.

**Comment by micha-f** [comment]
```
> @operational/components@0.1.0-14 lint /home/travis/build/Contiamo/operational-ui/packages/components
> tslint './src/**/*.{ts,tsx}' --fix
Fixed 1 error(s) in src/Breakdown.tsx
Fixed 1 error(s) in src/SidebarHeader.tsx
```
This is what travis outputs. So we're running it with --fix? It certainly should fail in this case but did not.

**Comment by peterszerzo** [comment]
Woups, I didn't explain it properly: we do run it with `--fix` and `--write`, but then if any of the files wind up changing in the end as per `git diff`, we throw an error in https://github.com/Contiamo/operational-ui/blob/master/scripts/ensure-clean-repo.sh. It has been reliable over the past two months.

**Comment by micha-f** [comment]
That makes sense
