### ISSUE TITLE
Textarea improvements

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#403]
- [ ] A `disabled` prop that toggles the disabled state of the textarea would be useful.
- [ ] When the `height` is set using the `css` prop, the height of the container is adjusted rather than the height of the textarea itself. This seems a little counter-intuitive because, as a user, I would expect the height of the textarea itself to change.
  - It would be nice generally if the `css` prop was spread into the textarea's styles as opposed to the styles of its container.
- [ ] The `css` prop expects `CSSProperties` but also should expect `(props: any) => CSSProperties` that would allow one to use the theme in there.

**Comment by peterszerzo** [comment]
I think in general it should be difficult to touch the components' internals in order to set some limits to flexibility and maintain consistent looks across codebases. Passing down `css` prop to the `textarea` instead of the container, as well as allowing `theme` injection in the `css` prop both go against that, and I would favor removing the need to resort to them by improving internal implementations.

As a start, you can already manipulate the height of the textarea by doing `<Textarea css={{ "& textarea": { height: 320 }} />`. Since that is obviously too complicated for routine use, I can think of these solutions:

* explicit `height` prop outside `css`: it is an important styling setting whose existence as a special prop could be justified.
* doing an internal trick to detect if there is a numerical `height` field inside the `css` prop. If there is one, the textarea's height can be set to `calc(100% - 20px)` or `whateverTheHeightInCssIs - 20`. The implementation for this turns quite messy if we allow `({ theme }: { theme: Theme }) => `-like functions to be passed as `css`, certainly doable, just not sure it's worth it.

What do you think, @TejasQ?

**Comment by peterszerzo** [comment]
Actually, totally changed my mind about the implementation of the trick being messy. See it end-to-end in the related PR.

**Comment by TejasQ** [comment]
I agree with you. Looks good to me!
