### ISSUE TITLE
AvatarGroup improvements

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#477]
![image](https://user-images.githubusercontent.com/9947422/40926090-a7c747e0-681b-11e8-9bdf-c027dd7e5b7b.png)

We'd need to enhance the `AvatarGroup` a bit by truncating its children. By default, we would display a maximum of `4` avatars. If there is an `avatars` prop passed in with length > `4`, the last element is replaced with a circle in the primary color, containing `+${avatar.length -3}` that invokes whatever the `onMoreClick` prop tells it to.

## Proposed API
```jsx
<AvatarGroup
  avatars={[]} 
  renderTooltip={avatar => <>{avatar.name}</>}
  onMoreClick={() => doSomething()}
/>
```

### What happens onClick of an Avatar?
Nothing, for now.

### What happens onMouseEnter of an Avatar?
We display whatever the `renderTooltip` says.

### What happens onClick of (+5)?
We do whatever `onMoreClick` says.

### Should the list expand?
No.

**Comment by micha-f** [comment]
I think it makes sense to make the number of displayed pictures configurable. That doesn't seem so difficult to implement and just fixing it to 3 seems rather arbitrary.

**Comment by fabien0102** [comment]
@micha-f It is totally arbitrary but it's by design 😈 . Since we want to build an "opiniated" ui kit we believed that is a good idea to restrict the freedom of the user of the ui kit.

One of the benefit is to have only one rule over all the applications, and this rule is on the operational-ui side (so it's easier to have consistency over the application)

After I'm also agree, it's not hard to implement, the really question is: do we want this part configurable by the user or not? (opiniated or freedom) :wink:

**Comment by micha-f** [comment]
I think that in some places it might actually look better to display 5 avatars. I don't think we should hardcode to 3 here.

**Comment by TejasQ** [comment]
I think hardcoding is flawed by design and ought to be avoided. If we want to provide a good, opinionated set of UI components, I think we ought to provide _reasonable defaults_ with allowing a user to override it to suit whatever his/her use case or design may require.

**Comment by micha-f** [comment]
I like it! - that's what I had in mind :)
