### ISSUE TITLE
Improve Modal API

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#622]
Ref: #620

### Concept
The idea is to have almost the same API as `Confirm` (with the hope to share more logics between the two components).

With this API, we don't need anymore to deal with the `isOpen` state when we use the `Modal` component, and we can have multiple modals in the same page easily.

### API Proposal
```tsx
interface ModalOptions {
  title?: React.ReactNode
  body: React.ReactNode
  onClose?: () => void
}

interface Props {
  children: (modal: (options: ModalOptions) => void) => React.ReactNode
}
```

### Example of usage
```jsx
<Page title="Delete the internet">
  <Modal>
    {modal => (
      <Card title="Show me your modal!">
        <Button
          color="error"
          onClick={() =>
            modal({
              title: "I'm the title, and I'm optional",
              body: (
                <>
                  <p>I'm a modal</p>
                </>
              ),
              onClose: () => alert("closed!"),
            })
          }
        >
          Open the modal
        </Button>
      </Card>
    )}
  </Modal>
</Page>
```

**Comment by fabien0102** [comment]
@TejasQ I think that my solution is more "two and more modals friendly" and is the same as `Confirm` (so I need to transform a `Modal` to `Confirm`, it's an easy refactor).

I also try to be consistant with our existing API 😉

**Comment by TejasQ** [comment]
I revisited the current API for `Confirm` and I'm not sure why we're passing properties of the `Confirm` modal to its invocation function _instead_ of as `props` to confirm.

I think `<Confirm title="" prop1="something else">` is _more_ idiomatic than defining the `Confirm` component's _props_ inside `confirm()`. The `body`, however, I think is _more_ readable inside the `confirm()` block. This is what my suggestion tries to address.

I think my counter solution is _also_ "two and more modals friendly", but is a little more explicit: every time there's a `<Modal`, you can expect a Modal to be triggered.

I would be more careful with your approach because, from your proposal, one `<Modal` could give a user many different kinds of modals based on the invocation function.
