### ISSUE TITLE
FIX THE SPINNER COLOR ON BUTTONS

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#659]
## The Problem
Currently, we have an issue with buttons that contain spinners that have non-white backgrounds. [Play here](http://operational-ui.netlify.com/#!/Button).

You'll want to change the background color of a spinning button in the playground to be something non-white to see the issue.

![image](https://user-images.githubusercontent.com/9947422/43667903-6135b878-977a-11e8-9947-634e07eddc51.png)

## The Fix

`./src/Button/Button.tsx` should style the `<Spinner />` in it to be `<Spinner color={readableTextColor(buttonColor)} />`.

```diff
-<Spinner />
+<Spinner color={readableTextColor(buttonColor)} />
```

**Comment by peterszerzo** [comment]
This broke because the `currentColor` assignment was removed from `Spinner` - shall we instead reconsider whether we should just add it back and fix our default spinner color assignment some other way, like an explicit `defaultColor` prop on the spinner?

**Comment by TejasQ** [comment]
I think using `currentColor`:

a) is unpredictable and breaks opinionation of Operational UI, rendering spinners that magically take the text color of their containers,

b) does not clearly describe intent to color the spinner at the codebase level.

For these reasons, I do not think using `currentColor` makes sense and recommend explicity setting values in order to avoid surprises going forward, while maintaining the opinionated-nature of Operational.

**Comment by fabien0102** [comment]
I think that the spinner color should follow the same pattern that any text in a button (so use the magic function)

So I'm in the flavour of the following fix also :wink:

```diff
-<Spinner />
+<Spinner color={readableTextColor(buttonColor)} />
```

**Comment by peterszerzo** [comment]
I disagree. Using `currentColor` is more predictable than the hard-coded alternative, in a sense that it guarantees consistency between the colors of different elements through inheritance, without relying on explicit settings that break things between contexts (like it did in this issue).

The spinner does not clearly describe the intent of the spinner color because there is no clear one intent. Sure, there is a default color, but the spinner should adapt to context in a way that is flexible.
