### ISSUE TITLE
I can't scroll on a huge error message…

### ISSUE THREAD

**Issue by fabien0102** [contiamo/operational-ui#664]
![image](https://user-images.githubusercontent.com/1761469/43848909-52209f16-9b34-11e8-932b-847baa1ed6a3.png)

Very hard to debug with the actual screen ^^

**Comment by TejasQ** [comment]
This shouldn't be possible, because the [heading should say "Something Went Wrong"](https://github.com/contiamo/operational-ui/blob/master/src/Internals/ErrorBoundary.tsx#L45), and [the stack trace should be scrollable](https://github.com/contiamo/operational-ui/blob/master/src/Internals/ErrorBoundary.tsx#L22).

**Comment by fabien0102** [comment]
The problem is on the error message between the `something went wrong` and the stack trace ;)

Sine the error message is already duplicate in the stacktrace, I think that we can simply remove this one from the header or truncate it :wink:

**Comment by TejasQ** [comment]
Will fix.
