### ISSUE TITLE
Add fallback to `window` in order to support SSR

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#684]
Currently, `OperationalUI` uses a lot of properties on `window.` to handle resize, etc. The problem here is that when we try to render Operational UIs server-side, there _is no `window` object_ and so the entire app breaks.

Solving this is a one-liner and would just add a fallback to an empty object to the component.

**Comment by adeelibr** [comment]
Reference: https://stackoverflow.com/a/2671217/4921319

Wouldn't it be better if we removed `window.` all together & instead use `document.body.` to bind event listeners. 

> Webkit and mozilla browsers seem to be happy with either, but IE doesn't respond to most events registered on the window, so you need to use document to work with IE

Also as a fact I can tell that in React-Material-UI they are not using `window.` to bind event handlers. I am assuming it for the same reason as this for SSR support.

**Comment by TejasQ** [comment]
`document.body.` presents the same problem in a node environment unless some type of JSDom abstraction is used, right? I'm not sure that solves the problem.

How does React-Material-UI attach event handlers while maintaining SSR?

I think the easiest solution would be:

`var window = window || { addEventListener: () => {} }` at the top of `OperationalUI.tsx`.

**Comment by adeelibr** [comment]
On checking the `Input` component, `autoComplete` prop is already available. 😅 

Typings are already added

https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Input/Input.tsx#L29

And then used here like

https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Input/Input.tsx#L238

https://github.com/contiamo/operational-ui/blob/67ab23ed89f16e8e92286d0bfeba5cb7b713ed2a/src/Input/Input.tsx#L250

**Comment by adeelibr** [comment]
Although while looking at the code, I think `Input` should be self contained, while the component that take `Input` along with `label` should be a separate component. What do you think?

**Comment by adeelibr** [comment]
> document.body. presents the same problem in a node environment unless some type of JSDom abstraction is used, right? I'm not sure that solves the problem.

I don't think so, since in SSR when you hydrate the ReactDOM you set it with `document.getElementById('app`)` So I think `document.body` is available on a Node instance as well. I went through the entire Material UI code base. They are simply attaching event's to `document.body` without any check like.

> var window = window || { addEventListener: () => {} }

There are some places in that library which uses this helper library https://github.com/react-bootstrap/dom-helpers

If you think adding an extra check like `window || { addEventListener: () => {} }` this would be helpful. I'd be more then happy to add a PR for this.

**Comment by adeelibr** [comment]
> document.body. presents the same problem in a node environment unless some type of JSDom abstraction is used, right? I'm not sure that solves the problem.

In entire Material UI code base. They are simply attaching event's to `document.body` without any check like.

> var window = window || { addEventListener: () => {} }

There are some places in that library which uses this helper library https://github.com/react-bootstrap/dom-helpers but for attaching events, they aren't using this as well.

If you think adding an extra check like `window || { addEventListener: () => {} }` this would be helpful. I'd be more then happy to add a PR for this.

**Comment by adeelibr** [comment]
Another suggestion of this would be to have a polyfill for this injected at the root of our build, something like this

```
if (typeof window === 'undefined') {
    global.window = {}
}
```

So instead of manually doing this in  every component, it is going to be available everywhere. Your thoughts?

**Comment by adeelibr** [comment]
New take on things 😁 😅 Forget what I said before 😛 lol

I created a SSR app, just to be sure of the entire process. The window & document object is available in SSR. With a slight catch. If you go through the rendering process. Unless or until the `render()` method isn't called. The 'document' object isn't available because it has not been rendered. So my advice for this would be to use 

```
document.body.
```
`document.body` instead of `window` because IE doesn't work with `window` in some cases. And both Chrome, Firefox can handle `document.body` and it is supported in `IE` as well.

My 2 cents will be to use the life cycle in the entire UI library accordingly. Call 'document.body.` after the UI has rendered and not before that. Otherwise it will not work. This is the same approach that Material UI uses as well.

Your thoughts?

**Comment by TejasQ** [comment]
Great work, @adeelibr! Let's do that.

**Comment by adeelibr** [comment]
Awesome, I'll start working on it. And create a PR.
