### ISSUE TITLE
Dealing with unstyled text

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#708]
# Problem
So we currently use React components that render regular old text DOM nodes a la `<h1>`, `<span>`, etc.. By default, we _do not_ style these nodes in Operational, but instead expose a suite of Typography components: `<Body>`, `<Heading1>`, etc. that _are_ among the former nodes but with styling.

Because of this, the regular old DOM nodes are unstyled. This looks pretty ugly.

# Proposed Solution
I've thought of the following two solutions:

## Solution 1: `<StyledText>`
A component that wraps _whatever_ is in it, and applies the same styling as `Heading1` does to `h1`s to the underlying DOM node. In terms of implementation, it would be 

```jsx
const StyledText = styled("div")`
  h1 {
    whatever happens in Heading1's styles here
  }

  span {
    you get the idea
  }
`
```

Anything in that `div` would then look as expected. I am not in favor of this approach because:
1. It adds an extra node to the DOM and to the React tree.
1. _Still_ allows breaking Operational's opinionation because we'll have unstyled text in places where this has been forgotten.

## Solution 2: Using `<OperationalUI>` the way it was intended
If we hoist these styling settings to the top-level provider, we have an opinionated library that styles _all text_ out of the box, and does not require wrapping text in React components like React Native does. 

I feel this is more of an idiomatic approach: wrap once, forget about it – your text is always beautiful.

Thoughts?

**Comment by peterszerzo** [comment]
I find solution 1 more in line with the styled components philosophy, where styles are localized and we don't have to worry about which global style fights which other global or local style. Have we identified a need for other contexts in which opinionated static-markup styles are required, other than one in which I put some rendered markdown inside a `<StyledText>` tag? If not, I think it's best to keep these styles scoped. Otherwise, we can look into re-using this component or creating another before adding more to our global styles.

**Comment by fabien0102** [comment]
Why just not using `<Heading1>` and `<Body>` as originally design? For me you should always use a react component for styling text instead of `<h1>` or `<span>`.

I propose to add a ts-lint rule of somebody is using a native dom balise in our project to enforce this rule 🤠

**Comment by TejasQ** [comment]
> So we currently use React components that render regular old text DOM nodes

@fabien0102 , we use React Markdown in some places, that parses Markdown and renders raw `<h1>`s. There is no way around this unless we write our own markdown parser for Operational.

@peterszerzo I agree, but I don't see why the styles cannot be localized at a higher level, at `<OperationalUI>`. Could you explain a little more about why scoping by `StyledText` is more optimal than the former? 🤔

**Comment by fabien0102** [comment]
I'm totally in favor of having an abstraction of React markdown in operational ui, exactly like our `Code` component. For me `OperationalUI` should only style his own components, if I'm using an external dependency, I don't want to have OperationalUI style.

For now we only have h1 unstyled in React markdown, but if tomorrow we want to another amazing library out of the box, that used h1 with a specific style, I don't want any unwanted overload from our Operational UI :wink:

**Comment by fabien0102** [comment]
"opinionated library" ≠ styled every other libraries for you

We should provided opinionated components, but scoped! Otherwise it's the beginning of the specificity css war! (And I don't want this kind of war in my projects ^^)

**Comment by ImogenF** [comment]
I agree, we don't want a CSS war. We had this to a certain extent in the old frontiamo and metriamo repos - trying to figure out where a particular bit of CSS came from originally, or why specific CSS wasn't being applied, was a nightmare at times.

**Comment by TejasQ** [comment]
Still, I'm in the other camp here: I believe _anything_ inside `<OperationalUI>` needs to predictably _look_ like Operational UI – it should _own_ the appearance of its children. All its children. This will prevent a CSS war actually because everything inside Operational should look the way we want it to. That said, I'm not sure there's a solid way to guarantee predictable styles down the tree and a war might in fact ensue. 

It seems the scoped approach is what the majority of us is comfortable with and I can't find a strong enough case for my preference so let's go in that direction. 🙂 

I'll update the issue with a proposed API shortly.

**Comment by peterszerzo** [comment]
@TejasQ the advantage of localizing at a lower level is that it is much less likely for CSS rule conflicts and overrides to occur between global `p` styles and styles a random `p` tag gets through its local parent component. In the current intended usage at least, it is unlikely that we'll put other components inside `<StyledText>`, whereas if we add the styles to `<OperationalUI>`, global styles will apply to every component.

This is indeed convenient, but it is also dangerous, and I think we should be really careful with introducing possible overrides. What will happen when we change the `Heading1` component and open it up for an override it previously protected itself from? What happens when something changes in the `emotion` implementation that will render the global styles after the local ones, causing our apps to look different after an overnight patch release? Are we willing to spend extra time debugging style regressions?

I'm sure there are reassuring answers to these concerns, but I'd rather avoid thinking about them in the first place.

**Comment by TejasQ** [comment]
Closing in favor of #755
