### ISSUE TITLE
Topbar API improvements

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#872]
Given the current Topbar API:

https://github.com/contiamo/operational-ui/blob/880ca84580361e5ead3a5a72ac25e2b650ca7c82/src/TopbarSelect/TopbarSelect.tsx#L10-L14

I propose Topbar to be improved in the following ways:

- `selected` expects a "selected value", but just expects a `string`. I'd like this to be a `ContextMenuItem` so then I can add an icon in there in order to achieve this:

![image](https://user-images.githubusercontent.com/9947422/50006094-dfdc1380-ffac-11e8-970c-0978c4479b72.png)

**Comment by peterszerzo** [comment]
That's a good direction - though instead of duplicating the `ContextMenuItem` that we're already adding in `items`, we can just keep the `value` prop as a string and do a lookup from items based on that. Otherwise we're opening the door for inconsistent state bugs.

In that spirit, I also don't think that the current `onChange?: (newLabel: string | React.ReactElement<any>) => void` type definition is very useful, because you can't do anything with a `ReactElement` other than render it imperatively somewhere else. They should all be strings I'd say.

Shall we take care of both in a PR?

**Comment by TejasQ** [comment]
> though instead of duplicating the ContextMenuItem that we're already adding in items, we can just keep the value prop as a string and do a lookup from items based on that. 

Yes. Great idea!

**Comment by TejasQ** [comment]
Closing because stale.
