### ISSUE TITLE
Any plans on moving to hooks?

### ISSUE THREAD

**Issue by adeelibr** [contiamo/operational-ui#908]
With hooks coming out of alpha version soon, is there a road map in place to move/migrate all Class components to hooks. With hooks everything is a function.

**Comment by fabien0102** [comment]
We will probably move to hooks here 😉 We already use them in production 👼 

But regarding the strategy, I don't really see the point to rewrite everything in hooks style (since the library API is the same) However it can be nice to have a hook version of our context component (to avoid nestead render props 😄 )

So let's begin by `OperationalContext`, rest are just for library confort. Also I will prefer to keep render props and hooks style, so don't break everything 🤠 

@adeelibr Are you interest to take this feature?
@TejasQ What do you think about this strategy?

**Comment by TejasQ** [comment]
@fabien0102 I like your idea. Let's queue this for v14 as it will be a great breaking change. Step 1 is to update the `peerDependencies` entry for React to be `^16.8`. 😄

**Comment by TejasQ** [comment]
@adeelibr, to add to @fabien0102's great answer to your question, here's a nice todo list if you're interested in contributing: https://github.com/contiamo/operational-ui/issues/908

I'd suggest discussing further there. Please close this issue if you agree, or feel free to carry on the conversation here.

**Comment by adeelibr** [comment]
> @adeelibr Are you interest to take this feature?

I would love to 👍 @fabien0102 

> @adeelibr, to add to @fabien0102's great answer to your question, here's a nice todo list if you're interested in contributing: #908 I'd suggest discussing further there.

This is issue #908 😅 @TejasQ

**Comment by TejasQ** [comment]
Oops, I meant #910 😂

**Comment by adeelibr** [comment]
Great! I am closing this issue in favor of #910, I'd like to start of working with `OperationalContext` initially.
