### ISSUE TITLE
Broken link on documentation site

### ISSUE THREAD

**Issue by brentbaum** [contiamo/operational-ui#936]
Visiting the project home page and clicking "Docs" doesn't work (the browser remains on the home page), so I can't see your beautiful component library.

**Comment by TejasQ** [comment]
Hey Brent! Thanks for the report! We're currently working on a comprehensive overhaul of our docs. We expect to ship it this Tuesday. 😄

**Comment by JoshRosenstein** [comment]
@TejasQ - will you be bumping styleguidist to v9? Wonder since you need to now explicitly import the components within the examples, if that help out performance or not. I think the main issue with current setup is that everything is loaded in at once and navigation is only anchors. where as [storybook](https://baseui.design/components/input/) or [doz](https://rosenstein.io/emotion-icons/usage-props)- 
can separate out by pages. Not too familiar with styleguidist.

after typing that ^ i dug into their api and found [pagepersection](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#pagepersection)- so that might help. The only issue now would having to manually list all files and sections in the config

**Comment by TejasQ** [comment]
@JoshRosenstein - that's really cool. I'm actually chipping away at a styleguidist clone that is more suited to our needs. It's coming along nicely but still has some rough edges (read: it's ready but doesn't quite get hot module replacement correctly). 

Great finding the pagepersection though – that could be a nice interim solution!

**Comment by JoshRosenstein** [comment]
@TejasQ - I was just playing around with it. I stripped away the custom components besides the wrapper- just to test out the pagepersection. It is so much faster! haha.
Also found out you dont need to type all components out, each component within the section is its own page. Heres my [branch ](https://github.com/JoshRosenstein/operational-ui/tree/docs-withPages) i was testing with

![Alt Text](https://i.imgur.com/xrkpRnd.gif)

**Comment by TejasQ** [comment]
@JoshRosenstein that's incredible! Let's merge it, but please keep the markdown files untouched and let's change only the styleguide since we're gonna be moving it over soon.

**Comment by JoshRosenstein** [comment]
Merge into your update-docs branch? well theres really not much I did but comment out a few lines in the config, and upgraded deps. I wouldnt have been able to test that out if you didnt prep those READMEs 😉

**Comment by TejasQ** [comment]
Ah, thanks. Maybe do a fork of my branch with the READMEs + your changes and let's merge to `master`?

**Comment by JoshRosenstein** [comment]
My original fork was from yours, at its current state its def not ready for master merge unless you want out-of the box styleguidist site. Im not sure if your wanting to try to fix your custom renders or not, but the best way to do it is first remove all the custom styleguidist components besides the wrapper, verify all demos rendered, determine Page and section convention, then go into your custom components and rewire the routing api and whatever else that was going on. 

This is what I [have forked](https://github.com/contiamo/operational-ui/compare/update-docs...JoshRosenstein:docs-withPages) and played around with.

If your branch is that one `operational-ui/update-docs`, then I guess i'll rebase mine back to yours, and commit only the configuration changes, since i have other undocumented changes, and merge it into your branch that way you can address whatever goals you have.

**Comment by JoshRosenstein** [comment]
@TejasQ - going through each component on site with upgraded version, to catch which components have an error. Looks like im having to remove the typing's from the examples in order to render

**Comment by TejasQ** [comment]
@JoshRosenstein this is fine. Let's do it.
